# Generated by Django 5.0.2 on 2024-03-02 01:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=120)),
                ('school_name', models.CharField(choices=[('J', 'Junior St Michal High School'), ('S', 'St karence Montensary Public School'), ('D', 'Doon Public School')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='Name', max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10, message='mobile number must be at least 10 digit long'), django.core.validators.RegexValidator('^9\\d{9,14}', message='The nuber must be started with 9 and contain aat least 10 digit long')])),
                ('age', models.CharField(max_length=100)),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
        ),
    ]
